services:
  mongodb:
    container_name: MongoDB
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  go-app:
    container_name: GOProject
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017
      MONGO_DATABASE: ${MONGO_DB}
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
